<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE brutes [
	<!ELEMENT brutes (brute)*>
	<!ELEMENT brute (name, choice*, next?, choice*, bifurq?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT choice (#PCDATA)>
	<!ELEMENT bifurq (c1, c2)>
	<!ATTLIST bifurq current-tree (c1 | c2) #IMPLIED>
	<!ELEMENT c1 (picked, choice*, next?, choice*, bifurq?)>
	<!ELEMENT c2 (picked, choice*, next?, choice*, bifurq?)>
	<!ELEMENT picked (#PCDATA)>
	<!ELEMENT next (#PCDATA)>
]>
<brutes>
	<brute>
		<name>MissPHP</name>
		<choice>FH,Force</choice>
		<choice>AM,Endu</choice>
		<choice>Fouet,Endu</choice>
		<choice>Sai,Endu</choice>
		<choice>Endu,Glaive</choice>
		<choice>Force,Glaive</choice>
		<choice>Force,Massue</choice>
		<choice>TdC,Force</choice>
		<choice>Endu,Massue</choice>
		<choice>Endu,Massue</choice>
		<choice>Endu,Chien</choice>
		<choice>Rapi_Force,Endu</choice>
		<choice>Armure,Agi</choice>
		<choice>Force,Massue</choice>
		<choice>Contre,Agi</choice>
		<choice>FE,Force</choice>
		<choice>SC,Agi</choice>
		<choice>6e.s,Endu</choice>
		<choice>Agi,Baton</choice>
		<choice>Force,Massue</choice>
		<bifurq current-tree="c2">
			<c1>
				<picked>Rapi</picked>
				<choice>Force,Lance</choice>
				<choice>Endu,Glaive</choice>
				<choice>Agi,Glaive</choice>
				<choice>Perse,Endu</choice>
				<choice>Rapi,Trident</choice>
				<choice>Force,Glaive</choice>
				<choice>Agi,Shushu</choice>
				<choice>Endu,Baton</choice>
				<choice>Agi,Chien</choice>
				<choice>Force,Chien</choice>
				<choice>Rapi,Baton</choice>
				<choice>Force,Baton</choice>
				<choice>Endu,Hache</choice>
			</c1>
			<c2>
				<picked>Chien</picked>
				<choice>SqP,Agi</choice>
				<choice>Endu,Fleau</choice>
				<choice>Agi,Renfort</choice>
				<choice>Force_Agi,Agi</choice>
				<choice>Filet,Agi</choice>
				<choice>Rapi,Baton</choice>
				<choice>Endu,Massue</choice>
				<choice>Agi,Glaive</choice>
				<choice>Endu,PR</choice>
				<choice>BF,Force</choice>
				<choice>Endu,Baton</choice>
				<choice>Choc,Agi</choice>
				<choice>Endu,Marteau</choice>
				<choice>Force,Bombe</choice>
				<choice>Force,Agi_Force</choice>
				<choice>Agi,PR</choice>
				<choice>Force,Glaive</choice>
				<choice>Force,Glaive</choice>
				<choice>Rapi_Agi,Endu</choice>
				<choice>Endu,Hache</choice>
				<choice>Force,Glaive</choice>
				<choice>Agi,Baton</choice>
				<choice>Endu,Baton</choice>
				<choice>Force,Etoile</choice>
				<choice>Force_Endu,Endu</choice>
				<choice>Agi,Massue</choice>
				<choice>Vanda,Endu</choice>
				<choice>Force,Lance</choice>
				<choice>Rapi,Agi_Endu</choice>
				<choice>Bouclier,Rapi</choice>
				<choice>Rapi,Trident</choice>
				<choice>Force,Agi_Rapi</choice>
				<choice>Agi,Lance</choice>
				<choice>Trappeur,Agi</choice>
				<choice>Force,Endu_Rapi</choice>
				<choice>Endu,Massue</choice>
				<choice>Force,Agi_Force</choice>
				<choice>Survie,Force</choice>
				<choice>Force,Massue</choice>
				<choice>Force,Hache</choice>
				<choice>Rapi,Ragi_Force</choice>
				<choice>Agi,Baton</choice>
				<choice>Endu_Rapi,Rapi</choice>
				<choice>Rapi,Baton</choice>
				<choice>PT,Force</choice>
				<choice>Rapi,Glaive</choice>
				<choice>Rapi,Shushu</choice>
				<choice>Force_Rapi,Endu</choice>
				<choice>Rapi,Baton</choice>
				<choice>Endu,Os</choice>
				<choice>Hypnose,Agi</choice>
				<choice>Rapi,Glaive</choice>
				<choice>Rapi,Endu_Agi</choice>
				<choice>Force,Hache</choice>
				<choice>Rapi,Endu_Rapi</choice>
				<next />
			</c2>
		</bifurq>
	</brute>
	
	<brute>
		<name>MisterPHP</name>
		<choice>BF,Rapi</choice>
		<choice>FH,Force</choice>
		<choice>PR,Rapi</choice>
		<choice>Endu,Baton</choice>
		<choice>Rapi,Hache</choice>
		<choice>AM,Endu</choice>
		<choice>Agi,Couteau</choice>
		<bifurq current-tree="c2">
			<c1>
				<picked>Rapi</picked>
				<choice>Endu,Shushu</choice>
				<choice>Agi,Baton</choice>
				<choice>Rapi,Trident</choice>
				<choice>Rapi,Massue</choice>
				<choice>Armure,Force</choice>
				<choice>Force,Couteau</choice>
				<choice>Force,Choice</choice>
				<choice>Agi,Couteau</choice>
				<choice>Force,Glaive</choice>
				<choice>Endu,Trident</choice>
				<choice>Endu,Massue</choice>
				<choice>Perse,Endu</choice>
				<choice>Increvable,Force</choice>
				<choice>Filet,Agi</choice>
				<choice>Force,Baton</choice>
				<choice>Rapi,Baton</choice>
				<choice>Rapi,Trident</choice>
				<choice>Rapi,Cuisinier</choice>
			</c1>
			<c2>
				<picked>CqP</picked>
				<choice>Rapi,Couteau</choice>
				<choice>Rapi,Renforts</choice>
				<choice>Rapi,Lance</choice>
				<choice>Agi,Massue</choice>
				<next />
			</c2>
		</bifurq>
	</brute>
	
	<brute>
		<name>MisterJS</name>
		<bifurq current-tree="c1">
			<c1>
				<picked>Trappeur</picked>
				<choice>AdF,Force</choice>
				<choice>Chien,Endu</choice>
				<next />
				<choice>Sai,Endu</choice>
				<choice>AM,Agi</choice>
				<choice>Force,Os</choice>
				<choice>Rapi,Renforts</choice>
				<choice>BF,Rapi</choice>
				<choice>Force,Baton</choice>
				<choice>PT,Endu</choice>
				<choice>Endu,Couteau</choice>
				<choice>Force,Lance</choice>
				<choice>Endu,Lance</choice>
				<choice>Agi,Baton</choice>
				<bifurq current-tree="c1">
					<c1>
						<picked>Trident</picked>
						<choice>Bouclier,Endu</choice>
						<choice>6e.s,Force</choice>
						<choice>MA,Force</choice>
						<choice>Intouchable,Rapi</choice>
						<bifurq current-tree="c1">
							<c1>
								<picked>Rapi</picked>
								<choice>Rapi,PR</choice>
								<choice>Contre,Rapi</choice>
								<choice>Rapi,Lance</choice>
								<choice>Glaive,Rapi</choice>
							</c1>
							<c2>
								<picked>Endu_Rapi</picked>
								<choice>Glaive,Force</choice>
							</c2>
						</bifurq>
					</c1>
					<c2>
						<picked>Agi</picked>
						<choice>Endu,PR</choice>
						<choice>Rapi,Os</choice>
						<choice>Rapi,Massue</choice>
						<choice>Rapi,Couteau</choice>
						<choice>Rapi,Glaive</choice>
						<choice>Force,PR</choice>
						<choice>Force,Os</choice>
						<choice>Agi,GB</choice>
						<choice>Force_Endu,Agi</choice>
						<choice>Increvable,Endu</choice>
						<choice>Cimeterre,Force</choice>
					</c2>
				</bifurq>
			</c1>
			<c2>
				<picked>Agi</picked>
				<choice>Perse,Agi</choice>
				<choice>Endu,FE</choice>
				<choice>Vita,Rapi</choice>
				<choice>Endu,Baton</choice>
				<choice>Cimeterre,Endu</choice>
				<choice>Rapi,Hache</choice>
				<choice>Sai,Endu</choice>
				<choice>Endu,Hache</choice>
				<choice>PT,Force</choice>
				<choice>Bouclier,Rapi</choice>
				<choice>Force,Glaive</choice>
				<choice>Agi,Couteau</choice>
				<choice>Rapi,CqP</choice>
				<choice>Agi,Baton</choice>
				<choice>Endu,Baton</choice>
				<choice>Rapi,Lance</choice>
				<choice>Rapi,Couteau</choice>
				<choice>Rapi,Couteau</choice>
				<choice>Agi,Trident</choice>
				<choice>AM,Endu</choice>
				<choice>Contre,Agi</choice>
				<choice>Agi,Hache</choice>
				<choice>Force,6e.s</choice>
				<choice>Rapi,Baton</choice>
				<choice>Force,Lance</choice>
				<choice>Couteau,Rapi</choice>
				<choice>Agi,Os</choice>
				<choice>Endu,Rapi_Agi</choice>
			</c2>
		</bifurq>
	</brute>
	
	<brute>
		<name>MissJS</name>
		<choice>Chien,Agi</choice>
		<choice>Force,Couteau</choice>
		<choice>Chien,Agi</choice>
		<choice>Agi,Baton</choice>
		<choice>Force,Hache</choice>
		<choice>Force,AdF</choice>
		<choice>Force,Rapi_Endu</choice>
		<next />
		<choice>AM,Rapi</choice>
		<choice>FH,Rapi</choice>
		<choice>Endu,Glaive</choice>
		<choice>BF,Force</choice>
		<choice>Agi,Os</choice>
		<choice>Endu_Agi,Rapi</choice>
		<choice>Endu,Rapi_Endu</choice>
		<choice>Agi,Espion</choice>
		<choice>Endu,Glaive</choice>
		<choice>Voleur,Rapi</choice>
		<choice>Force,PR</choice>
		<choice>Force,Baton</choice>
		<choice>Rapi,Baton</choice>
		<choice>Cimeterre,Force</choice>
		<choice>Endu,Hache</choice>
		<choice>Panthere,Agi</choice>
	</brute>
	
	<brute>
		<name>MissPython</name>
		<choice>FH,Endu</choice>
		<choice>Vanda,Endu</choice>
		<choice>Perse,Endu</choice>
		<choice>BF,Agi</choice>
		<choice>Endu_Agi,Rapi</choice>
		<choice>Agi,Lance</choice>
		<choice>Rapi,Baton</choice>
		<choice>Rapi,Shushu</choice>
		<choice>Cimeterre,Force</choice>
		<choice>Endu,Os</choice>
		<choice>Force,Hache</choice>
		<choice>Agi,Massue</choice>
		<next />
	</brute>

	<brute>
		<name>MisterPython</name>
		<choice>Force,Baton</choice>
		<choice>Vita,Agi</choice>
		<choice>AM,Rapi</choice>
		<bifurq current-tree="c2">
			<c1>
				<picked>GB</picked>
				<choice>Force,Baton</choice>
				<choice>Force,Lance</choice>
				<choice>Endu,Espion</choice>
				<choice>Rapi,Couteau</choice>
				<choice>Endu,Glaive</choice>
				<choice>SC,Agi</choice>
				<choice>Agi,Hache</choice>
				<choice>Agi,Glaive</choice>
				<choice>Endu,Chien</choice>
				<choice>Endu,Couteau</choice>
				<choice>Filet,Agi</choice>
				<choice>Shushu,Force</choice>
				<choice>MP,Endu</choice>
				<choice>Rapi,Couteau</choice>
				<choice>Agi,Couteau</choice>
				<choice>Rapi,6e.s</choice>
				<choice>6e.s,Rapi</choice>
				<choice>Marteau,Agi</choice>
				<choice>Force,Rapi_Endu</choice>
				<choice>Force_Agi,Agi</choice>
				<choice>Force,Glaive</choice>
				<choice>Endu,Couteau</choice>
				<choice>Endu,Couteau</choice>
				<choice>Agi,Os</choice>
				<choice>Bouclier,Endu</choice>
				<choice>Force,Glaive</choice>
			</c1>
			<c2>
				<picked>Agi</picked>
				<choice>Contre,Agi</choice>
				<choice>Endu,Hache</choice>
				<choice>Chien,Endu</choice>
				<choice>Force_Rapi,Agi</choice>
				<choice>Agi,Glaive</choice>
				<choice>Rapi,Baton</choice>
				<choice>BF,Rapi</choice>
				<next />
			</c2>
		</bifurq>
	</brute>
	
	<brute>
		<name>MissC</name>
		<choice>Force,Couteau</choice>
		<choice>Endu,Baton</choice>
		<choice>Force,Baton</choice>
		<choice>PR,Force</choice>
		<choice>6e.s,Endu</choice>
		<choice>Contre,Agi</choice>
		<choice>Chien,Force</choice>
		<choice>Voleur,Rapi</choice>
		<choice>Agi,Couteau</choice>
		<choice>Force,Medit</choice>
		<choice>Endu,Couteau</choice>
		<choice>Agi,FE</choice>
		<choice>Agi,Baton</choice>
		<choice>Endu,Couteau</choice>
		<choice>Endu,FE</choice>
		<next />
	</brute>
	
	<brute>
		<name>MisterC++</name>
		<choice>AM,Endu</choice>
		<choice>Force,Hache</choice>
		<choice>Endu,Couteau</choice>
		<bifurq current-tree="c1">
			<c1>
				<picked>Force</picked>
				<bifurq current-tree="c1">
					<c1>
						<picked>Force</picked>
						<choice>Force,Massue</choice>
						<bifurq current-tree="c2">
							<c1>
								<picked>Agi</picked>
								<bifurq>
									<c1>
										<picked>Endu</picked>
										<choice>AdF,Endu</choice>
										<choice>Endu,Baton</choice>
										<choice>Endu,Baton</choice>
										<choice>Rapi,Lance</choice>
									</c1>
									<c2>
										<picked>PT</picked>
										<choice>Vita,Agi</choice>
										<choice>Endu,Epee</choice>
										<choice>Filet,Rapi</choice>
										<choice>Force,BF</choice>
										<choice>Force,Lance</choice>
										<choice>Rapi,Glaive</choice>
										<choice>Force,Couteau</choice>
										<choice>Force,Epee</choice>
										<choice>Renforts,Rapi</choice>
										<choice>Force,Couteau</choice>
										<choice>Bouclier,Agi</choice>
										<choice>Trappeur,Rapi</choice>
										<choice>Rapi,Baton</choice>
										<choice>Force,Endu_Agi</choice>
										<choice>Lance,Rapi</choice>
									</c2>
								</bifurq>
							</c1>
							<c2>
								<picked>Couteau</picked>
								<choice>Force,Filet</choice>
								<choice>Force,Hache</choice>
								<choice>BF,Agi</choice>
								<choice>FH,Agi</choice>
								<choice>Force,Etoile</choice>
								<next />
								<choice>Rapi,Espion</choice>
								<choice>Ours,Force</choice>
								<choice>TdC,Endu</choice>
								<choice>FE,Force</choice>
								<choice>Ballerines,Force</choice>
								<choice>Agi_Endu,Force</choice>
								<choice>SC,Rapi</choice>
								<choice>Force,Glaive</choice>
								<choice>Rapi,Massue</choice>
								<choice>Endu_Rapi,Agi</choice>
								<choice>Pugnace,Force</choice>
								<choice>Force_Rapi,Rapi</choice>
								<choice>Rapi,Os</choice>
								<choice>Force,Lance</choice>
								<choice>Force_Endu,Rapi</choice>
							</c2>
						</bifurq>
					</c1>
					<c2>
						<picked>PT</picked>
						<choice>Vita,Agi</choice>
						<choice>Force,Baton</choice>
						<choice>Filet,Agi</choice>
						<choice>Endu,Couteau</choice>
						<choice>Endu,Massue</choice>
						<choice>Rapi,6e.s</choice>
						<choice>Renforts,Agi</choice>
						<choice>Rapi,Glaive</choice>
						<choice>Endu,Baton</choice>
						<choice>Force,Rapi_Force</choice>
						<choice>Endu,6e.s</choice>
						<choice>Endu,Lance</choice>
						<choice>Fouet,Endu</choice>
						<choice>Agi,Survie</choice>
						<choice>Agi,Hache</choice>
					</c2>
				</bifurq>
			</c1>
			<c2>
				<picked>AdF</picked>
				<choice>Agi,6e.s</choice>
				<choice>Rapi,Lance</choice>
				<choice>Force,Pugnace</choice>
				<choice>Choc,Unknown</choice>
				<choice>Endu,Baton</choice>
			</c2>
		</bifurq>
	</brute>
	
	<brute>
		<name>MissC++</name>
		<choice>Vita,Endu</choice>
		<choice>Bouclier,Force</choice>
		<choice>Rapi,Massue</choice>
		<choice>Endu,PR</choice>
		<choice>Force,Massue</choice>
		<choice>Endu,Hache</choice>
		<choice>BF,Agi</choice>
		<choice>Sai,Agi</choice>
		<choice>Force,Chien</choice>
		<choice>Chien,Agi</choice>
		<choice>Force,Glaive</choice>
		<choice>Force,Glaive</choice>
		<choice>Force,CqP</choice>
		<choice>Force,Glaive</choice>
		<choice>Bombe,Agi</choice>
		<choice>Force,Hache</choice>
		<choice>Armure,Endu</choice>
		<choice>Agi,Os</choice>
		<choice>Force,Glaive</choice>
		<next />
		<choice>Force,Glaive</choice>
		<choice>PR,Agi</choice>
		<choice>Contre,Force</choice>
		<choice>AM,Rapi</choice>
		<choice>Endu,Os</choice>
		<choice>Rapi,GB</choice>
		<choice>Rapi,Baton</choice>
		<choice>Agi,Baton</choice>
	</brute>
	
	<brute>
		<name>MissJava</name>
		<choice>Choc,Endu</choice>
		<choice>Force,Choc</choice>
		<choice>Vita,Rapi</choice>
		<choice>Agi,Massue</choice>
		<choice>Etoile,Rapi</choice>
		<choice>Force,Hache</choice>
		<choice>Force,Massue</choice>
		<choice>AM,Agi</choice>
		<choice>BF,Force</choice>
		<choice>Rapi,Baton</choice>
		<choice>Force,Couteau</choice>
		<choice>Bouclier,Rapi</choice>
		<choice>Regen,Agi</choice>
		<choice>Endu,Massue</choice>
		<choice>Rapi,Hache</choice>
		<choice>TdF,Force</choice>
		<choice>Rapi,Deluge</choice>
		<choice>Force,Couteau</choice>
		<choice>Force,Couteau</choice>
		<choice>Agi,Glaive</choice>
		<choice>Agi,Trident</choice>
		<choice>Rapi,Massue</choice>
		<choice>Force,Massue</choice>
		<choice>Agi,Glaive</choice>
		<choice>FH,Agi</choice>
		<choice>Force,Glaive</choice>
		<choice>Force,Os</choice>
		<choice>Rapi,PR</choice>
		<next />
	</brute>
	
	<brute>
		<name>MisterJava</name>
		<choice>Fleau,Endu</choice>
		<choice>AdF,Endu</choice>
		<choice>Epee,Agi</choice>
		<choice>Rapi,Hache</choice>
		<choice>Force,Couteau</choice>
		<choice>Endu,Glaive</choice>
		<choice>Endu,Glaive</choice>
		<choice>Endu,Cuisinier</choice>
		<choice>Bouclier,Rapi</choice>
		<choice>Immo,Agi</choice>
		<choice>Agi,Os</choice>
		<choice>Force,Massue</choice>
		<choice>Endu,Baton</choice>
		<choice>Intouchable,Force</choice>
		<bifurq current-tree="c1">
			<c1>
				<picked>Force</picked>
				<choice>Agi,Glaive</choice>
				<choice>Endu,Hache</choice>
				<choice>Endu,Couteau</choice>
				<choice>Endu,Massue</choice>
				<choice>Force,Baton</choice>
				<choice>Agi,Hache</choice>
				<choice>Agi,Couteau</choice>
				<choice>Force,Lance</choice>
				<choice>MP,Endu</choice>
				<choice>Force,Lance</choice>
			</c1>
			<c2>
				<picked>Lance</picked>
				<choice>Endu,PR</choice>
				<bifurq current-tree="c2">
					<c1>
						<picked>Rapi</picked>
						<choice>Agi,Massue</choice>
						<choice>Agi,Glaive</choice>
						<choice>Agi,Couteau</choice>
						<choice>6e.s,Endu</choice>
						<choice>Agi,Chien</choice>
						<choice>Force,Baton</choice>
					</c1>
					
					<c2>
						<picked>Bombe</picked>
						<choice>Endu,Glaive</choice>
						<choice>Force,Baton</choice>
						<choice>Endu,PR</choice>
						<next />
					</c2>
				</bifurq>
			</c2>
		</bifurq>
	</brute>
	
	<brute>
		<name>MissOCaml</name>
		<choice>FH,Endu</choice>
		<choice>Force,Lance</choice>
		<choice>PT,Endu</choice>
		<choice>Fouet,Agi</choice>
		<bifurq current-tree="c2">
			<c1>
				<picked>Agi</picked>
				<choice>Endu,Baton</choice>
				<choice>Rapi,Couteau</choice>
				<choice>Force,Couteau</choice>
				<choice>Endu,hache</choice>
				<choice>Agi,Baton</choice>
				<choice>Force,Hache</choice>
				<choice>Ballerines,Agi</choice>
				<choice>Lance,Agi</choice>
				<choice>SC,Force</choice>
				<choice>Rapi,Couteau</choice>
				<choice>Agi,Baton</choice>
				<choice>Rapi,Massue</choice>
				<choice>Force,Couteau</choice>
				<choice>Endu,Hache</choice>
			</c1>
			<c2>
				<picked>PR</picked>
				<choice>Rapi,Couteau</choice>
				<choice>Choc,Rapi</choice>
				<choice>Endu,Couteau</choice>
				<choice>TdC,Agi</choice>
				<choice>Agi,Lance</choice>
				<choice>Agi,Os</choice>
				<choice>Increvable,Force</choice>
				<choice>Force,Baton</choice>
				<choice>Force,Lance</choice>
				<choice>Endu,Chien</choice>
				<choice>6e.s,Agi</choice>
				<choice>Force,Deluge</choice>
				<next />
				<choice>Endu,Couteau</choice>
				<choice>Rapi,Filet</choice>
				<choice>BF,Force</choice>
				<choice>SC,Agi</choice>
				<choice>Force,Massue</choice>
				<choice>Contre,Endu</choice>
				<choice>Bouclier,Agi</choice>
				<choice>Contre,Endu</choice>
				<choice>Force_Rapi,Agi</choice>
				<choice>Force_Agi,Rapi</choice>
				<choice>Agi,Couteau</choice>
				<choice>Endu_Rapi,Agi</choice>
			</c2>
		</bifurq>
	</brute>

	<brute>
		<name>MissSQL</name>
		<choice>Agi,Baton</choice>
		<choice>AdF,Force</choice>
		<choice>Agi,Glaive</choice>
		<choice>Bouclier,Rapi</choice>
		<choice>Voleur,Endu</choice>
		<choice>Endu,Baton</choice>
		<choice>Agi_Force,Endu</choice>
		<choice>Survie,Endu</choice>
		<choice>SC,Agi</choice>
		<choice>Sai,Agi</choice>
		<choice>Endu,Couteau</choice>
		<choice>PT,Endu</choice>
		<next />
		<choice>Force,Glaive</choice>
		<choice>Agi,Trident</choice>
		<choice>Endu,Shushu</choice>
		<choice>MA,Endu</choice>
		<bifurq current-tree="c2">
			<c1>
				<picked>Agi</picked>
				<choice>Endu,Couteau</choice>
				<choice>Filet,Endu</choice>
				<choice>Glaive,Rapi</choice>
				<choice>GB,Endu</choice>
				<choice>Agi_Force,Endu</choice>
				<choice>Chien,Agi</choice>
			</c1>
			<c2>
				<picked>Glaive</picked>
				<choice>Agi,Baton</choice>
				<choice>Force,Rapi_Agi</choice>
				<choice>Endu,Os</choice>
				<choice>Chien,Endu</choice>
				<choice>Force,Hache</choice>
				<choice>Contre,Rapi</choice>
				<choice>Rapi,Hache</choice>
				<choice>Chien,Agi</choice>
				<choice>Endu,Hache</choice>
			</c2>
		</bifurq>
	</brute>
	
	<brute>
		<name>MisterOCaml</name>
		<choice>Force,FE</choice>
		<choice>FH,Rapi</choice>
		<choice>Rapi,Ballerines</choice>
		<choice>Force,6e.s</choice>
		<choice>Rapi,Baton</choice>
		<choice>Sai,Endu</choice>
		<choice>AM,Force</choice>
		<choice>Endu,Massue</choice>
		<choice>Force,Endu_Agi</choice>
		<next />
		<choice>TdC,Rapi</choice>
		<choice>Agi,Baton</choice>
		<choice>Agi,Baton</choice>
		<choice>Endu,Trident</choice>
		<choice>Force,Baton</choice>
		<choice>Vanda,Force</choice>
		<choice>Rapi,PR</choice>
		<choice>Force,Couteau</choice>
		<bifurq current-tree="c2">
			<c1>
				<picked>Endu</picked>
				<choice>Force,Baton</choice>
				<choice>Rapi,Couteau</choice>
				<choice>Rapi,Couteau</choice>
				<choice>Rapi,Lance</choice>
				<choice>Choc,Force</choice>
				<choice>Contre,Rapi</choice>
			</c1>
			<c2>
				<picked>Ballerines</picked>
				<choice>Force,6e.s</choice>
				<choice>Agi,Marteau</choice>
				<choice>Couteau,Force</choice>
				<choice>PR,Agi</choice>
				<choice>Agi,Lance</choice>
				<choice>Force,Lance</choice>
				<choice>Force,Rapi_Force</choice>
			</c2>
		</bifurq>
	</brute>
	
	<brute>
		<name>MisterSQL</name>
		<choice>PR,Agi</choice>
		<choice>Bouclier,Endu</choice>
		<choice>Vanda,Agi</choice>
		<choice>Contre,Agi</choice>
		<choice>Vita,Agi</choice>
		<bifurq current-tree="c2">
			<c1>
				<picked>6e.s</picked>
				<choice>TdC,Force</choice>
				<bifurq>
					<c1>
						<picked>Glaive</picked>
						<bifurq>
							<c1>
								<picked>BF</picked>
								<choice>Force,Baton</choice>
								<choice>Agi,Baton</choice>
								<choice>Force_Agi,Rapi</choice>
								<choice>Endu,GB</choice>
								<choice>PT,Rapi</choice>
								<choice>Force,Baton</choice>
								<choice>Endu,Massue</choice>
								<choice>Endu,Lance</choice>
								<choice>Rapi,Agi_Endu</choice>
								<choice>Endu,Lance</choice>
								<choice>Rapi,Massue</choice>
								<choice>Force_Rapi,Rapi</choice>
								<choice>Endu,Rapi_Force</choice>
							</c1>
							<c2>
								<picked>Endu</picked>
								<choice>PT,Force</choice>
								<choice>Endu,Lance</choice>
								<choice>Force_Endu,Endu</choice>
								<choice>Agi,Baton</choice>
								<choice>Chien,Endu</choice>
								<choice>Force,Hache</choice>
								<choice>Rapi,Couteau</choice>
								<choice>Panthere,Rapi</choice>
								<choice>Agi,Massue</choice>
								<choice>Force_Endu,Endu</choice>
								<choice>Rapi,Massue</choice>
								<choice>Agi,Baton</choice>
								<choice>Force,Filet</choice>
								<choice>Force,Agi_Force</choice>
								<choice>Chien,Force</choice>
								<choice>Force_Rapi,Agi</choice>
								<choice>Force,Rapi_Force</choice>
								<choice>Agi_Endu,Force</choice>
								<choice>BF,Agi</choice>
							</c2>
						</bifurq>
					</c1>
					<c2>
						<picked>Rapi</picked>
						<choice>Regen,Endu</choice>
						<choice>Agi,Glaive</choice>
						<choice>Endu,Glaive</choice>
						<choice>Choc,Agi</choice>
						<choice>Glaive,Agi</choice>
						<choice>Force,Epee</choice>
						<choice>Rapi_Force,Agi</choice>
						<choice>Rapi_Force,Agi</choice>
						<choice>Agi,Shushu</choice>
						<choice>Endu,Massue</choice>
						<choice>Agi,Lance</choice>
						<choice>Rapi,Massue</choice>
						<choice>Endu_Force,Agi</choice>
						<choice>Endu,Agi_Force</choice>
					</c2>
				</bifurq>
			</c1>
			<c2>
				<picked>Agi</picked>
				<choice>Choc,Rapi</choice>
				<choice>Rapi,Baton</choice>
				<bifurq current-tree="c2">
					<c1>
						<picked>Bombe</picked>
						<choice>Endu,Baton</choice>
						<choice>Endu,Baton</choice>
						<choice>Endu,Massue</choice>
						<choice>Lance,Agi</choice>
						<choice>Endu,Hache</choice>
						<choice>Force,Glaive</choice>
						<choice>Force_Rapi,Endu</choice>
						<choice>Force,Filet</choice>
						<choice>Chien,Force</choice>
						<choice>Agi,Massue</choice>
						<choice>Rapi,Filet</choice>
						<choice>Glaive,Endu</choice>
						<choice>Endu,Massue</choice>
						<choice>Force,Rapi_Agi</choice>
						<choice>Force_Rapi,Agi</choice>
						<choice>Force,Agi_Endu</choice>
					</c1>
					<c2>
						<picked>Agi</picked>
						<next />
					</c2>
				</bifurq>
			</c2>
		</bifurq>
	</brute>
	
	<brute>
		<name>MissJulia</name>
		<choice>Force,Baton</choice>
		<choice>Endu,Baton</choice>
		<choice>Bouclier,Rapi</choice>
		<choice>6e.s,Agi</choice>
		<choice>MA,Force</choice>
		<choice>Force,Baton</choice>
		<bifurq current-tree="c2">
			<c1>
				<picked>Glaive</picked>
				<choice>Force,Endu_Agi</choice>
				<choice>Rapi,Baton</choice>
				<choice>Force,Endu_Force</choice>
				<choice>Agi,Massue</choice>
				<choice>Chien,Rapi</choice>
				<choice>FH,Force</choice>
				<choice>PR,Rapi</choice>
				<choice>Agi,Lance</choice>
				<choice>Endu,Force_Endu</choice>
				<choice>Agi,Rapi_Agi</choice>
				<choice>Rapi,Agi_Rapi</choice>
				<choice>Agi,Massue</choice>
				<choice>Force,Agi_Rapi</choice>
				<choice>BF,Agi</choice>
				<choice>Endu_Force,Rapi</choice>
			</c1>
			<c2>
				<picked>Force</picked>
				<choice>Glaive,Endu</choice>
				<choice>Force,Lance</choice>
				<choice>Filet,Endu</choice>
				<choice>Agi,Baton</choice>
				<choice>Endu,Baton</choice>
				<choice>Force,CqP</choice>
				<choice>AdF,Force</choice>
				<choice>Hallebarde,Agi</choice>
				<choice>Agi,Baton</choice>
				<choice>Choc,Agi</choice>
				<next />
				<choice>Agi,Rapi_Force</choice>
				<choice>Endu_Agi,Rapi</choice>
				<choice>Agi,Baton</choice>
				<choice>AM,Endu</choice>
			</c2>
		</bifurq>
	</brute>

	<brute>
		<name>MissScala</name>
		<choice>MA,Force</choice>
		<choice>Endu,Bombe</choice>
		<choice>Ballerines,Force</choice>
		<choice>FH,Force</choice>
		<choice>Rapi,Os</choice>
		<choice>AM,Rapi</choice>
		<choice>Force,Medit</choice>
		<bifurq current-tree="c2">
			<c1>
				<picked>BF</picked>
				<choice>Endu,Hache</choice>
				<choice>Rapi,Filet</choice>
				<choice>Rapi,Hache</choice>
				<choice>Agi,Bombe</choice>
				<choice>Sai,Rapi</choice>
				<choice>PT,Agi</choice>
			</c1>
			<c2>
				<picked>Rapi</picked>
				<bifurq current-tree="c2">
					<c1>
						<picked>Agi</picked>
						<choice>Rapi,Bombe</choice>
						<choice>Choc,Rapi</choice>
						<choice>Endu,Lance</choice>
						<choice>Force,CqP</choice>
						<choice>TdC,Force</choice>
						<choice>PR,Rapi</choice>
						<choice>6e.s,Agi</choice>
						<choice>Force,Rapi_Endu</choice>
						<choice>Endu,Baton</choice>
						<choice>Endu_Force,Agi</choice>
						<choice>Glaive,Endu</choice>
						<choice>Cimeterre,Rapi</choice>
						<choice>Force,Hache</choice>
						<choice>Endu,Baton</choice>
					</c1>
					<c2>
						<picked>6e.s</picked>
						<choice>BF,Force</choice>
						<choice>Choc,Rapi</choice>
						<choice>TdC,Rapi</choice>
						<choice>PR,Agi</choice>
						<choice>Agi,Lance</choice>
						<choice>Survie,Rapi</choice>
						<choice>Bouclier,Endu</choice>
						<choice>Increvable,Agi</choice>
						<choice>Force_Rapi,Endu</choice>
						<choice>Glaive,Rapi</choice>
						<next />
					</c2>
				</bifurq>
			</c2>
		</bifurq>
	</brute>

	<brute>
		<name>MisterJulia</name>
		<choice>Vita,Rapi</choice>
		<choice>Agi,Trident</choice>
		<choice>PT,Force</choice>
		<choice>Force,Hache</choice>
		<choice>Sai,Endu</choice>
		<choice>Agi,Glaive</choice>
		<bifurq current-tree="c2">
			<c1>
				<picked>Rapi</picked>
				<choice>Endu,Lance</choice>
				<choice>Endu,Hache</choice>
				<choice>Agi,Hache</choice>
				<choice>Bombe,Agi</choice>
				<choice>Force,Hache</choice>
				<choice>Endu,Filet</choice>
				<choice>Force,Baton</choice>
				<choice>Agi,Hache</choice>
				<choice>Endu,Glaive</choice>
				<choice>FH,Rapi</choice>
			</c1>
			<c2>
				<picked>Couteau</picked>
				<choice>Agi,Filet</choice>
				<choice>Agi,Os</choice>
				<choice>Rapi,Baton</choice>
				<choice>Rapi,Hache</choice>
				<choice>Force,Hache</choice>
				<choice>Choc,Force</choice>
				<choice>Endu,Force_Rapi</choice>
				<choice>PR,Rapi</choice>
				<choice>Rapi,Lance</choice>
				<choice>Rapi_Agi,Agi</choice>
				<choice>Endu,Massue</choice>
				<next />
			</c2>
		</bifurq>
	</brute>

	<brute>
		<name>MissJSP</name>
		<choice>FH,Endu</choice>
		<choice>BF,Agi</choice>
		<choice>Filet,Agi</choice>
		<choice>Force,Glaive</choice>
		<choice>Force,Baton</choice>
		<choice>AM,Rapi</choice>
		<choice>Chien,Agi</choice>
		<choice>Agi,Massue</choice>
		<choice>Fleau,Force</choice>
		<choice>Rapi,Shushu</choice>
		<choice>Agi,Lance</choice>
		<choice>6e.s,Agi</choice>
		<choice>Endu,Force_Agi</choice>
		<choice>Endu,Massue</choice>
		<choice>Chien,Rapi</choice>
		<choice>Force,Massue</choice>
		<next />
		<choice>TdC,Agi</choice>
		<choice>Endu,Os</choice>
		<choice>Force,Massue</choice>
		<choice>Agi,Hache</choice>
		<choice>Agi,Massue</choice>
		<choice>Endu,Glaive</choice>
		<choice>Force,PR</choice>
		<choice>Endu,Baton</choice>
	</brute>

	<brute>
		<name>MissMaven</name>
		<choice>SqP,Rapi</choice>
		<choice>Force,FE</choice>
		<choice>Rapi,FE</choice>
		<choice>Cimeterre,Rapi</choice>
		<choice>Agi,Baton</choice>
		<choice>Voleur,Endu</choice>
		<choice>FE,Agi</choice>
		<choice>Force,Massue</choice>
		<choice>Rapi,Glaive</choice>
		<choice>TdF,Rapi</choice>
		<choice>Endu,PR</choice>
		<choice>Chien,Agi</choice>
		<choice>Agi,Hallebarde</choice>
		<choice>Agi,Glaive</choice>
		<choice>Rapi,Lance</choice>
		<choice>Force,Glaive</choice>
		<choice>Agi,Lance</choice>
		<choice>Bouclier,Force</choice>
		<next />
		<choice>Vanda,Endu</choice>
		<choice>Endu,Glaive</choice>
		<choice>BF,Rapi</choice>
		<choice>Ours,Endu</choice>
		<choice>Endu,Agi_Force</choice>
		<choice>Agi,Couteau</choice>
		<choice>Endu,Glaive</choice>
	</brute>

	<brute>
		<name>MissAngular</name>
		<choice>FH,Rapi</choice>
		<choice>BF,Rapi</choice>
		<choice>SqP,Agi</choice>
		<choice>MA,Rapi</choice>
		<choice>Force,Massue</choice>
		<choice>Couteau,Endu</choice>
		<choice>Rapi,Lance</choice>
		<choice>PR,Rapi</choice>
		<choice>Force_Endu,Endu</choice>
		<choice>Rapi,Cuisinier</choice>
		<choice>TdC,Agi</choice>
		<choice>Force_Agi,Agi</choice>
		<choice>Chien,Agi</choice>
		<choice>Contre,Force</choice>
		<choice>SC,Rapi</choice>
		<choice>Rapi,Agi_Force</choice>
		<next />
	</brute>

	<brute>
		<name>MissReact</name>
		<choice>Armure,Agi</choice>
		<choice>Chien,Endu</choice>
		<choice>AdF,Agi</choice>
		<choice>Agi,Saboteur</choice>
		<choice>Rapi,Baton</choice>
		<choice>Endu,Lance</choice>
		<choice>PR,Endu</choice>
		<choice>Force,Couteau</choice>
		<choice>Vita,Rapi</choice>
		<choice>SC,Agi</choice>
		<bifurq current-tree="c2">
			<c1>
				<picked>TdC</picked>
				<choice>Couteau,Agi</choice>
				<choice>Endu,Baton</choice>
				<choice>Contre,Endu</choice>
				<choice>Endu,Baton</choice>
				<choice>Endu,Shushu</choice>
				<choice>Sai,Endu</choice>
			</c1>
			<c2>
				<picked>Force</picked>
				<choice>Endu,Agi_Rapi</choice>
				<next />
			</c2>
		</bifurq>
	</brute>

	<brute>
		<name>MissVueJS</name>
		<choice>Vita,Endu</choice>
		<choice>Force,PR</choice>
		<choice>SqP,Rapi</choice>